# Generated by Django 3.1.6 on 2021-03-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deta', '0002_entre_fotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='entre',
            name='imagenes',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
